npm:
  image: node:0.10
  volumes:
    - source:/usr/src/app
  command: sh -c "cd /usr/src/app; npm install"

ipfs:
  image: jbenet/go-ipfs:latest
  volumes:
    - source:/usr/src/app

helloworldone:
  image: eris/decerver:browser
  environment:
   - SOURCE

helloworldtwo:
  image: eris/decerver:browser
  environment:
   - SOURCE

seleniumhub:
  image: selenium/hub:latest
  expose:
   - "4444"

seleniumnode:
  image: selenium/node-chrome:latest
  links:
   - seleniumhub:hub
   - helloworldone
   - helloworldtwo

helloworldtest:
  image: node:0.10
  links:
   - seleniumhub:selenium
  volumes:
    - test:/usr/src/app
  command: sh -c "cd /usr/src/app; npm install && npm test"
